version: "3.9"

services:
  prefect-server:
    image: prefecthq/prefect:3-latest
    command: prefect server start --host 0.0.0.0
    environment:
      - PREFECT_API_URL=http://0.0.0.0:4200/api
      - PREFECT_UI_API_URL=http://localhost:4200/api
    ports:
      - 4200:4200
    restart: unless-stopped

  daily-extractor:
    build:
      context: ./daily-extractor
    environment:
      - TZ=America/Sao_Paulo
    command: ["python", "main.py"]
    depends_on:
      - mongodb
      - prefect-server

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - TZ=America/Sao_Paulo
  
  mongo-express:
    image: mongo-express:latest
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - 4201:8081
    depends_on:
      - mongodb

volumes:
  mongo_data:
