version: "3.9"

services:
  daily-extractor:
    build:
      context: ./daily-extractor

    environment:
      - TZ=America/Sao_Paulo
    command: ["python", "main.py"]

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - TZ=America/Sao_Paulo

volumes:
  mongo_data:
